stages:
  - test
  - build
  - deploy
test job:
  stage: test
  script:
    - echo "test"
build job:
  stage: build
  script:
    - echo "built"
deploy job:
  stage: deploy
  script:
    - echo "deployed"